### PR TITLE
Apiv2 rebased - HRB tests

### PR DESCRIPTION
**Pull request by hburgund**

### CODE REVIEW

**Comment by 13rac1** [comment]
See the pull... not sure why it exists?

**Comment by hburgund** [comment]
This is just a test, as indicated in the title, so I can debug and try to make progress as @grayb seems to be unavailable currently and I need to get api/2 code merged ASAP. Don't worry, this PR will never be merged; it will be deleted, but I wanted a test PR in place so I could get Travis to run and test things.

**Comment by 13rac1** [comment]
Ok. My branches run travis on every commit. Not sure why yours don't. huh...

**Comment by hburgund** [comment]
closing...test over.

**Pull request closed without merging**
