### PR TITLE
Upgrade to Django 1.9

### PR DESCRIPTION
**Pull request by IllyaMoskvin**
This is a fairly extensive commit, since most of the requirements had
to be upgraded as well. Dependencies have been locked down to specific
versions for consistency and troubleshooting. Notable changes:
- Moved wsgi.py to a more standard location, updated apache config.
  Now referenced in roundware.settings.WSGI_APPLICATION
- For roundware.api2, implemented the new Application Configuration
  structure. See http://stackoverflow.com/q/32795227/1943591
- django-guardian now creates its own AnonymousUser in the database.
  Removed AnonymousUser references from fixtures to avoid conflicts.
  http://django-guardian.readthedocs.io/en/stable/configuration.html
- ManyToManyField no longer accepts null=True
- django.contrib.auth.models.User should not be accessed directly.
  Use django.conf.settings.AUTH_USER_MODEL instead
- Django changed the way it loads models, which broke streaming.
  Moving django.setup() in roundwared.rwstreamd fixed the issue.
- django_chartit is no longer maintained. Moved to django_chartit2
  This may require us to install jQuery and Highcharts manually
- django.forms.models.save_instance has been removed.
  We are now calling save() instead, but it might need more testing.
  https://github.com/django/django/commit/8656cf
  https://github.com/django/django/commit/b11564

### CODE REVIEW

**Comment by 13rac1** [comment]
Can you fix the merge conflicts?

It'll require a rebase to update this branch.

**Comment by IllyaMoskvin** [comment]
To be honest, I don't even know if I have write access to this repository. I also do not want to take responsibility for the final merge. I'm happy to advise and explain what's what, but I'll leave the final call to @hburgund.

**Comment by hburgund** [comment]
@IllyaMoskvin I will certainly take care of the merging once it is tested more and I'm comfortable with everything. 

I believe @eosrei is referring to the fact that your PR cannot be merged automatically since there are some conflicts with the current state of `develop`. We need you to resolve those conflicts first and then we can test and get it merged. Thanks a lot.

**Comment by 13rac1** [comment]
@hburgund Yes, plus Travis.ci will not run until the PR can be merged.

**Comment by IllyaMoskvin** [comment]
Hmm alright, so what I think I'll do is create a new branch on IMAmuseum/roundware-server that's based on the develop branch here as it is now, and then cherry pick this commit into it. Let me go ahead and close this request; I'll open up a new one shortly.

If after that it still cannot be merged automatically, I don't think there is anything else I can really do, but let me give that a shot first.

**Comment by 13rac1** [comment]
@IllyaMoskvin FWIW you can do all of that without closing this PR. Rebase your local branch, force push to your remote and it'll update this PR.

**Comment by IllyaMoskvin** [comment]
@eosrei Sorry, there was a lot of branch-shuffling and squashing involved. I'm mostly staying on top of things, but I'm not comfortable enough with git and GitHub yet to pull this off elegantly. Please see the new PR #283

**Pull request closed without merging**
