### PR TITLE
Update Vagrantfile to Ubuntu 16.04

### PR DESCRIPTION
**Pull request by jslootbeek**
Includes Postgres 9.5 with PostGIS 2.2.
to rebuilt Vagrant instance: vagrant halt && vagrant destroy && vagrant up.

### CODE REVIEW

**Comment by 13rac1** [comment]
Hmm.. Not sure what went wrong. I did:

```bash
git remote add jslootbeek git@github.com:jslootbeek/roundware-server.git
git remote update
git checkout ubuntu16.04 
vagrant up
```

Result:
```bash
==> default: Unpacking gstreamer0.10-plugins-bad:amd64 (0.10.23-8.1ubuntu3) ...
==> default: dpkg: dependency problems prevent configuration of gstreamer0.10-plugins-bad:amd64:
==> default:  gstreamer0.10-plugins-bad:amd64 depends on libcdaudio1 (>= 0.99.12p2); however:
==> default:   Package libcdaudio1 is not installed.
==> default:  gstreamer0.10-plugins-bad:amd64 depends on libgstreamer-plugins-bad0.10-0 (= 0.10.23-8.1ubuntu3); however:
==> default:   Package libgstreamer-plugins-bad0.10-0 is not installed.
==> default:  gstreamer0.10-plugins-bad:amd64 depends on libkate1 (>= 0.4.1); however:
==> default:   Package libkate1 is not installed.
==> default:  gstreamer0.10-plugins-bad:amd64 depends on libmimic0; however:
==> default:   Package libmimic0 is not installed.
==> default:  gstreamer0.10-plugins-bad:amd64 depends on libofa0 (>= 0.9.3); however:
==> default:   Package libofa0 is not installed.
==> default:  gstreamer0.10-plugins-bad:amd64 depends on libslv2-9 (>= 0.6.4-1~); however:
==> default:   Package libslv2-9 is not installed.
==> default:  gstreamer0.10-plugins-bad:amd64 depends on libsoundtouch0 (>= 1.8.0); however:
==> default:   Package libsoundtouch0 is not installed.
==> default:  gstreamer0.10-plugins-bad:amd64 depends on libspandsp2 (>= 0.0.6~pre18); however:
==> default:   Package lib
==> default: dpkg: error processing package gstreamer0.10-plugins-bad:amd64 (--install):
==> default:  dependency problems - leaving unconfigured
==> default: Processing triggers for libglib2.0-0:amd64 (2.48.2-0ubuntu1) ...
==> default: Errors were encountered while processing:
==> default:  gstreamer0.10-plugins-bad:amd64
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

**Comment by hburgund** [comment]
I haven't had a chance to test this yet, but will do so shortly and will report back to see if @eosrei's experience is replicated.

**Comment by hburgund** [comment]
I can now confirm that I get the same error as @eosrei, so I'm pretty confident there is something wrong.

@jslootbeek does it work for you on a fresh vagrant install?

I'm not surprised there are gstreamer issues since we are using the unsanctioned version. Looks like the problem is related to dependencies not being installed for `gstreamer0.10-plugins-bad`.  Is there a way to tell it to automatically install any missing dependencies as needed? 

I tried to install manually to test, but some had no install candidate suggesting to me that we might need to add some lines to `/etc/apt/sources.list` but I'm not sure which ones.

**Comment by hburgund** [comment]
## REMINDERS/QUESTIONS
* We should also either include the gstreamer plugins `.deb` files in the `files/` directory in the repo or delete the locally downloaded file after it is installed. Or I guess we could just make sure it is downloaded to the `files/` directory. Either way, what happens now is a bit messy to just download the two `.deb` files to the root `roundware-server` directory and leave them there.
* AMD vs x86? - we are going with amd in `vagrant` but not sure if this even matters, though I am concerned that the amd-specific `gstreamer-ugly` file we download won't work on a production machine that is not AMD?
* Upgrade vs. new install - Would an upgrade situation require the install of the special gstreamer plugins? Would the old ones still work or would they be over-written in the upgrade process?
* check google maps API key issue in admin
* why is `ubuntu-xenial-16.04-cloudimg-console.log` being added to git directory? Should clear out.

**Comment by hburgund** [comment]
I have done a full audit of the gstreamer plugins that Roundware uses - based on https://gstreamer.freedesktop.org/documentation/plugins.html - and here are the results:

### Core
* capsfilter
* filesrc

### Base
* adder
* vorbisenc
* oggmux
* audiotestsrc
* audioconvert
* audioresample
* volume

### Good
* audiopanorama
* taginject
* shout2send
* souphttpsrc
* wavparse

### Bad
* NONE

### Ugly
* lame

Given that I found no Bad plugins being used, I did a fresh install without them and then did a full set of manual stream operation tests and everything worked fine. Thus it appears that we no longer need the Bad plugins and can therefore circumvent the install issue outlined above.

I want to do more testing with an upgrade and bang on it more, but it's looking encouraging that we should be ok for the upgrade.

**Pull request closed without merging**
