### PR TITLE
Add ability to assign languages to projects

### LINKED ISSUE #309: Add languages field to Project model
For the new admin interface, we need a way to specify languages for each project. This will affect which localized strings you can add in other parts of the admin interface. We also need a way to toggle an "enabled" flag for languages on a project level. This allows editors to add a language to a project, but hide it from the public until all of the translations are ready.

Given that we already have a `Language` model, this shouldn't be terribly difficult server-side, but we will need to figure out a way to add an additional flag to the relationship (`enabled`). 

Sample expected APIv2 response, illustrating fields missing from `/api/2/projects/:id/`:

```
{
  "project_id": 1
  "name": "Test Project",
  [...]
  "languages": [
    {
      "id": 1,
      "enabled": true
    },
    {
      "id": 2,
      "enabled": false
    }
  ],
  [...]
}
```

### PR DESCRIPTION
**Pull request by hburgund**
Includes a bunch of ancillary items:

* admin screen updates
* data/schema migration - adds full name of base languages (en, es) and adds English as default language to any existing projects
* tested with upgrade as well as fresh install
* new default json fixture generated for fresh installs including new fields

Format of updated `api/2/projects/:id/` response (no changes to `api/1/`):
```
{
  "name": "Test Project",
  "latitude": 1,
  "longitude": 1,
...
  "languages": [
    1
  ],
...
  "project_id": 1
}
```

fixes #309

### CODE REVIEW

**Comment by IllyaMoskvin** [comment]
Looks good to me! I can handle the adding of English as default for new projects by sending an additional API call via the new admin.

**Review by IllyaMoskvin — APPROVED** [review]
Looks good to me! I can handle the adding of English as default for new projects by sending an additional API call via the new admin.

**Comment by hburgund** [comment]
@IllyaMoskvin thx for the review; I'm not sure we will need any validation on the admin side other than the standard required field validation as `project.languages` is required. Whatever you think works best for the admin is fine, but it might simply be enough to verify that all required fields are handled.

**Comment by IllyaMoskvin** [comment]
@hburgund That's a good point. Validation should do the trick. We still need to figure out how to `POST` _ALL_ the things, but that's a matter for another PR!

**Review by jslootbeek — APPROVED** [review]
This looks good. Pretty straight forward implementation.

**Pull request merged**
