### PR TITLE
upgrade djangorestframework to 3.0.4

### PR DESCRIPTION
**Pull request by grayb**
Changed the requirements and ran all prebuilt tests with success.  Please test this on change on your end.

### CODE REVIEW

**Comment by eosrei** [comment]
Have you tested the APIv1 calls? The existing unit tests only have 51% coverage. Existing REST API calls must be tested manually.

Do you have time to discuss my APIv2 documentation further? I do not consider that a complete document and it is not ready for implementation.

**Comment by grayb** [comment]
I have only ran the automated tests.  How do you recommend I perform the tests manually?  What is your usual process for that?

**Comment by eosrei** [comment]
Go to: http://localhost:8888/api/1/rest/ and confirm that the calls are working. They should be exactly the same as in the older DRF via curl. Don't need to test the APIv2 stubs yet though since nothing depends on them.

**Comment by hburgund** [comment]
Here are some urls I use for manual testing, in the order I typically test them.

get config:
```
http://localhost:8888/api/1?operation=get_config&project_id=1
```
then get tags:
```
http://localhost:8888/api/1?operation=get_tags&project_id=1
```
These will both return a nice JSON object with a bunch of data.  You can look at the RW API docs for more info on the expected responses: http://roundware.org/docs/api/index.html
then request a stream:
```
http://localhost:8888/api/1?operation=request_stream&session_id=1
```
this will return a stream mountpoint url that you can play in your browser.  
Modify it with tag filters:
```
http://localhost:8888/api/1?operation=modify_stream&session_id=1&tags=3,4,5,8,9,22
```
and move the listener:
```
http://localhost:8888/api/1?operation=move_listener&session_id=1&latitude=1&longitude=1
```
you should then hear voices filtering into the ambient music.  The default database only contains one audio asset.

If all of this works, things are looking good, but obviously this is only the most basic core functionality.  You can look at the RW logs at ```/var/log/roundware``` for more info on what's going on especially if something goes wrong.

I'm going to make a wiki page with this info as it'll be useful for others.

**Comment by hburgund** [comment]
I've done all of my basic manual tests on this code with the updated DRF and have tested out the minimal DRF api/1/rest/ requests and they all are working fine, so I think we are good to go with this update.

And on a related note, moving forward, could you do me a favor and use feature branches instead of local commits to and pull requests from ```develop```?  It just makes the process more complicated when I'm trying to test things as I get the old “there’s already a ‘develop’ branch, so you can’t checkout this one too” error in git.  Obviously I can rename branches and get around it, but I think it'll keep us all more organized to have the dev work be done on feature branches even if it's just a tiny thing like this update.  

@eosrei does a nice job of naming his branches with the issue number and a short description.  Let me know if this approach works for you.

**Comment by grayb** [comment]
Will do, thanks for the explanation.

**Pull request merged**
