### PR TITLE
APIv2 major milestone

### PR DESCRIPTION
**Pull request by grayb**
This is the cumulation of all APIv2 work done to date.

### CODE REVIEW

**Comment by 13rac1** [comment]
What testing procedures should we use to test this API? Will you be implementing unit tests for the new functionality?

**Comment by hburgund** [comment]
@grayb correct me if I'm wrong (when you're back from vacation!), but when we discussed this last week, you indicated that you will be working on adding unit tests for the new functionality such that the overall coverage isn't reduced by the addition of this new code.  It looks like you've got some stuff included here, but let us know the overall status/plans if you could.
@grayb did indicate that he's been running all of the current unit tests on an ongoing basis to ensure that none of them were broken by the api/2 work he's done.  All should be passing in this pull request.  There are manual testing procedures that I perform as a general rule, mainly using a real client to connect and run the basic RW functionalities and I will do that here as well before merging.

**Comment by hburgund** [comment]
What's the deal with the 0007_merge.py migration? https://github.com/roundware/roundware-server/pull/228/files#diff-e9cb2466f689daa7a23e9258b083a3ce
I'm no migration expert, but this seems superfluous?

**Comment by 13rac1** [comment]
Please add a summary to: https://github.com/roundware/roundware-server/blob/develop/CHANGELOG.txt

**Comment by hburgund** [comment]
I am experiencing an issue with the `modify_stream` api/1 call:

```
localhost:8888/api/1/?operation=modify_stream&session_id=1&tags=3,5,8,22
```

This doesn't filter the assets by tags.  The following debug line confirms that the tags simply don't make it into the actual request:

```
DEBUG <roundware.lib.api.modify_stream:262> {u'asset_id': [], u'tags': [], u'longitude': 1.0, u'session_id': [1], u'latitude': 1.0, u'project_id': []}
```

This same functionality seems to be fine for the api/2 call, just broken on api/1.  Probably just a simple variable passing issue somewhere?  Or always the possibility that something unique is happening on my local test VM, so confirmation would be great.

**Comment by hburgund** [comment]
Error with this call:

```
http://localhost:8888/api/1/?operation=add_asset_to_envelope&envelope_id=1&latitude=1&longitude=1&tags=3,5,8&mediatype=audio
```

I get a django-looking error response:

```
TypeError at /api/1/
<Asset: 10: audio at 1/1> is not JSON serializable
```

But interestingly, the asset does seem to get successfully added to the system.  Perhaps the error happens in some supplemental step that is now happening?  Maybe in the generation of the response JSON?  api/1 response should look something like:

```
{
    "success": True,
    "asset_id": 17
}
```

This response change causes the api/1 apps to think that the file upload/add was unsuccessful and therefore, the queuing mechanism tries over and over to upload.

**Comment by grayb** [comment]
@eosrei - I’m having problems testing the api endpoints that starts a stream.  It seems during the test, the rw_session table is missing.  So although I was able to bring in the fixture containing all the sample project data, this roundwared table didn’t get created.  I’ve been trying to figure out how to bootstrap roundwared and it’s testing tables from my testcase.

**Comment by 13rac1** [comment]
@grayb 

> It seems during the test, the rw_session table is missing.

The existing unit tests would not pass if rw_session wasn't created. Can you provide steps to reproduce? It exists in MySQL during the regular installation and in the sqlite during tests in my experience.

> So although I was able to bring in the fixture containing all the sample project data, this roundwared table didn’t get created. 

The sample project fixture is for users to have an example project. Are you using it for testing? The unit tests should follow the data creation procedures as used in the existing unit tests: https://github.com/roundware/roundware-server/blob/develop/tests/roundware/api1/test_commands.py 

``` python
    def setUp(self):
        super(type(self), TestServer).setUp(self)

        self.project1 = mommy.make(Project, name='Uno', recording_radius=10,
                                   id=12, audio_format='ogg',
                                   demo_stream_message_loc=[self.english_msg, self.spanish_msg],
                                   out_of_range_url='http://rw.com:8000/outofrange.mp3')
        self.session = mommy.make(Session, project=self.project1,
                                  language=self.spanish, id=1)
```

Another option we can upgrade to the newer methods described in the current Django documentation to avoid needing mommy.make(): https://docs.djangoproject.com/en/1.8/topics/testing/overview/

``` python
from django.test import TestCase
from myapp.models import Animal

class AnimalTestCase(TestCase):
    def setUp(self):
        Animal.objects.create(name="lion", sound="roar")
        Animal.objects.create(name="cat", sound="meow")

    def test_animals_can_speak(self):
        """Animals that can speak are correctly identified"""
        lion = Animal.objects.get(name="lion")
        cat = Animal.objects.get(name="cat")
        self.assertEqual(lion.speak(), 'The lion says "roar"')
        self.assertEqual(cat.speak(), 'The cat says "meow"')
```

> I’ve been trying to figure out how to bootstrap roundwared and it’s testing tables from my testcase.

This will require significant research. roundwared is not bootstrapped in the existing tests because it requires a human to listen to the output (until we bootstrap SkyNet!) You can test the specific functions separately, but a full bootstrap _probably_ needs to be done manually.

**Comment by 13rac1** [comment]
_I submit a slight update to the above after further research._

While I still think we should use the existing in-code unit test data creation procedure (or better the new method), it's acceptable to use fixtures if there is a separate test only fixture file. Data creation in code is easier to maintain as it doesn't require an import/change/export workflow to make changes.

Supporting documentation for Django test fixtures: http://django-testing-docs.readthedocs.org/en/latest/fixtures.html

**Comment by grayb** [comment]
On the API side, I was testing the endpoint that starts a stream, then returns the URL.  This is calling wait_for_stream, which times out, thus making it difficult to test the endpoint itself.  In the debug log I get `RoundException: Stream timeout on creation`.  Way above this in the testing code is this:

```
14:00:26 DEBUG <roundware.lib.api.apache_safe_daemon_subprocess:216> [u'/vagrant/roundware/settings/../../roundwared/rwstreamd.py', u'--session_id', '2', u'--project_id', '1']
14:00:26 DEBUG <roundware.lib.api.wait_for_stream:241> Checking for existence of stream 2MP3 on localhost:8000
14:00:29 DEBUG <roundwared.rwstreamd.create_daemon:145> Daemon PID 8042
14:00:29 DEBUG <roundwared.rwstreamd.thunk:38> {u'latitude': False, u'project_id': 1, u'longitude': False, u'session_id': 2, u'audio_stream_bitrate': 128}
14:00:29 DEBUG <roundwared.stream.__init__:34> Roundstream init: bitrate: 128
14:00:29 ERROR <roundwared.rwstreamd.start_stream:53> Traceback (most recent call last):
  File "/vagrant/roundware/settings/../../roundwared/rwstreamd.py", line 49, in start_stream
    stream = RoundStream(sessionid, audio_format, request)
  File "/vagrant/roundwared/stream.py", line 36, in __init__
    'project').get(id=sessionid)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/models/query.py", line 351, in get
    num = len(clone)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/models/query.py", line 122, in __len__
    self._fetch_all()
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/roundware/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such table: rw_session
```

Both errors only happen when I run the test that tries to start a stream.  I agree the error seems odd, all the other tests complete fine.

I had attempted to use the model creation code you cited first, but found it was not complete enough to fully test all the API endpoints I had created.  Having developed those endpoints using the sample project fixture, I figured it would be a good set of data to use for testing.  If we are to stick to in-code, I concur the new method is better.

**Comment by 13rac1** [comment]
> OperationalError: no such table: rw_session

My guess RoundwareD starts a new instance of python which means it gets a fresh new sqlite DB. The testing system is setup to use a temporary in-memory sqlite database. I'm not surprised a separate Python process doesn't have access to it.

This is yet-another problem with testing stream creation. It's going to be a huge process and probably not very fruitful to unit test the stream creation since we don't have SkyNet AI-type abilities to listen to it.

Solution: Don't test stream creation with the unit tests or travis.ci. Perhaps create a new `streamtest.py` for API2 to assist with automating the manual testing process like to API1? https://github.com/roundware/roundware-server/blob/cf9fafe0c65cd0757e2f33ca43b37f51a6dc642c/scripts/stream-test.py Have you used those automated manual tests? There's a whole group of CC audio available for upload tests: https://github.com/roundware/roundware-server/tree/cf9fafe0c65cd0757e2f33ca43b37f51a6dc642c/files/test-audio

> I had attempted to use the model creation code you cited first, but found it was not complete enough to fully test all the API endpoints I had created. 

I don't understand why it wouldn't be able to create all the data needed. Is there a bug in modelmommy? If it's failing to create some data we should figure out the cause. I've added a fair amount of new data in the tests using it. How did it fail?

> Having developed those endpoints using the sample project fixture, I figured it would be a good set of data to use for testing.

It seems fragile and more complex to maintain a fixture for unit testing. If you must use a fixture, please fork it from the existing sample data. I'd really prefer it in code though. There isn't much data in it. Honestly, I'd even make it for you if it came to that.

**Comment by hburgund** [comment]
this code is cleaned up and included in a future pull request #257 hence closing this one

**Pull request closed without merging**
